name: Pull request checks

on:
  pull_request:
    paths:
    - 'packages/js/**'

jobs:
  test:
    name: Test @telnyx/webrtc changes

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install
      run: npm ci && cd packages/js && npm ci
    - name: Test
      run: npm test
      env:
        CI: true
