name: Pull request checks

on:
  pull_request:
    paths:
    - 'packages/js/**'

jobs:
  test:
    name: Test @telnyx/webrtc changes

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install shared dependencies
      run: npm ci
    - name: Install package dependencies
      working-directory: packages/js
      run: npm ci
    - name: Test
      working-directory: packages/js
      run: npm test
      env:
        CI: true
