name: Pull request checks

on:
  pull_request:
    branches: [ $default-branch ]
    paths:
    - 'packages/js/**'

jobs:
  test:
    name: Test changes

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    defaults:
      run:
        working-directory: 'packages/js'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
      env:
        CI: true
