name: 'Publish release'

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        required: true
        default: 'webrtc'

jobs:
  publish-js:
    if: github.event.inputs.package == 'webrtc' || startsWith(github.ref, 'refs/tags/webrtc')

    name: '@telnyx/webrtc Publish release'

    runs-on: ubuntu-latest

    env:
      CI: true
      NPM_TOKEN: ${{ secrets.NPM_CI_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        # https://github.com/peter-evans/create-pull-request/issues/122
        ref: 'main'
        # https://github.com/release-it/release-it/issues/657#issuecomment-647848200
        fetch-depth: 0
    - name: Setup Git user
      # https://github.com/actions/checkout/issues/13
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install shared dependencies
      run: npm ci
    - name: Install package dependencies
      working-directory: packages/js
      run: npm ci --ignore-scripts
    - name: Generate .npmrc
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - name: Publish package
      working-directory: packages/js
      run: |
        npm run release -- \
        --ci \
        --no-github \
        --npm.skipChecks \
        --plugins.@release-it/conventional-changelog.infile=CHANGELOG.md
