name: 'Publish release'

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual trigger reason'
        required: false
        default: 'Manually triggered GitHub workflow'

jobs:
  publish-js:
    if: startsWith(github.ref, 'refs/tags/webrtc')

    name: '@telnyx/webrtc Publish release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ github.event.inputs.reason }}"
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install shared dependencies
      run: npm ci
    - name: Install package dependencies
      working-directory: packages/js
      run: npm ci --ignore-scripts
    - name: Publish package
      working-directory: packages/js
      run: npm publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
