name: '@telnyx/webrtc Test release'
on:
  pull_request:
    paths:
    - 'packages/js/**'
jobs:
  unit-tests:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # https://github.com/peter-evans/create-pull-request/issues/122
        ref: 'main'
        # https://github.com/release-it/release-it/issues/657#issuecomment-647848200
        fetch-depth: 0
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install shared dependencies
      run: npm ci
    - name: Install package dependencies
      working-directory: packages/js
      run: npm ci --ignore-scripts
    - name: Build
      working-directory: packages/js
      run: npm run build
    - name: Test
      working-directory: packages/js
      run: npm test
      env:
        CI: true
    - name: Install React Storybook
      working-directory: packages/js/examples/react-audio-widgets
      run: npm ci
      env:
        CI: true
    - name: Link React Storybook with SDK
      working-directory: packages/js/examples/react-audio-widgets
      run: npm run setup
      env:
        CI: true

  cypress-run-chrome:
    runs-on: ubuntu-16.04
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          env: STORYBOOK_USERNAME=${{ secrets.NPM_CI_STORYBOOK_USERNAME }},STORYBOOK_PASSWORD=${{ secrets.NPM_CI_STORYBOOK_PASSWORD }},STORYBOOK_DESTINATION=${{ secrets.NPM_CI_STORYBOOK_DESTINATION }}
      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Install Dependencies
        working-directory: packages/js/examples/react-audio-widgets
        run: npm install -D cypress  
      - name: Install shared dependencies
        working-directory: packages/js/examples/react-audio-widgets
        run: npm ci
      - name: Install package dependencies
        working-directory: packages/js/examples/react-audio-widgets
        run: npm ci --ignore-scripts
      - name: Test Chrome
        working-directory: packages/js/examples/react-audio-widgets
        run: npm run cypress:ci:chrome
        env:
          CI: true        

  build:
    name: Build SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # https://github.com/peter-evans/create-pull-request/issues/122
        ref: 'main'
        # https://github.com/release-it/release-it/issues/657#issuecomment-647848200
        fetch-depth: 0
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install shared dependencies
      run: npm ci
    - name: Install package dependencies
      working-directory: packages/js
      run: npm ci --ignore-scripts
    - name: Build
      working-directory: packages/js
      run: npm run build
